### ISSUE TITLE
UI scaling bug

### ISSUE THREAD

**Issue by DmitryMI** [DmitryMI/MathSprint#16]
MathTrial UI scaling working incorrectly

**Comment by DCPtime** [comment]
Появились менюшки, но кнопка проверить не работает.

**Comment by DCPtime** [comment]
Т.е вводишь чего-нибудь в поле ответа, нажимаешь проверить - и ничего не происходит.

**Comment by DCPtime** [comment]
Это относится только к 1-ой меню, при столкновении с мобами все норм.

**Comment by DCPtime** [comment]
Все, теперь норм.
